name: build
description: "Build the project"
runs:
  using: "composite"
  steps:
    - name: Config Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        paths:
          - node_modules
          - .next/cache/
        key: node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
